name: Build and Deploy Java Maven App

on:
  workflow_dispatch: # Trigger manually or via events

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java 17 environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: "temurin"
        java-package: jdk
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true
        job-status: success
        token: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests

    # Step 4: Upload the built artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/*.jar

    # Step 5: Deploy (example: to a server via SCP)
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USER }}
        APP_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp target/*.jar $USERNAME@$HOST:$APP_PATH
